[project]
name = "13-graph-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aman Prajapati", email = "amanprajapati22@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
13-graph-rag = "13_graph_rag:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
